spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/baby_trackr
    username: ${DB_MAIN_USERNAME}
    password: ${DB_MAIN_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update #automatically creates and updates tables based on your Kotlin entities
    properties:
      hibernate:
        type:
          json_format_mapper: jackson
    show-sql: true